### ISSUE TITLE
Test MirrorCheckTest.test_checklocation_model is failing

### ISSUE THREAD

**Issue by msAlcantara** [archlinux/archweb#285]
The test `mirrors.tests.test_mirrorcheck.MirrorCheckTest.test_checklocation_model` is failling when run all tests with `./manage.py test`, but when I run in isolation with `./manage.py test mirrors.tests.test_mirrorcheck.MirrorCheckTest.test_checklocation_model` pass.

Visualizing the code, I see that this test is about `mirrocheck` command, and `CheckLocation` id is informed using the flag `-l`, but the id `1`is hard coded, and when run all tests, some others tests create others `CheckLocation's`, and the id 1 can not existing more when `MirrorCheckTest.test_checklocation_model` run, and then an exception is raised.

```
ERROR: test_checklocation_model (mirrors.tests.test_mirrorcheck.MirrorCheckTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matheus/dev/github/archlinux/archweb/mirrors/tests/test_mirrorcheck.py", line 155, in test_checklocation_model
    call_command('mirrorcheck', '-l', '1')
  File "/home/matheus/dev/github/archlinux/archweb/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/home/matheus/dev/github/archlinux/archweb/venv/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/matheus/dev/github/archlinux/archweb/mirrors/management/commands/mirrorcheck.py", line 77, in handle
    location = CheckLocation.objects.get(id=location)
  File "/home/matheus/dev/github/archlinux/archweb/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/matheus/dev/github/archlinux/archweb/venv/lib/python3.6/site-packages/django/db/models/query.py", line 417, in get
    self.model._meta.object_name
mirrors.models.CheckLocation.DoesNotExist: CheckLocation matching query does not exist.
```

So, I think that should be more efficient to use `checkloc.id` instead '1'? 

Sorry if this make no sense, I just get started with the archweb project.

Update
- This only happens when is using postgres database, when using sqlite3 all tests pass

**Comment by jelly** [comment]
Thanks for the detailed report, resolved in https://github.com/archlinux/archweb/commit/31acd9bda779a77adfe598724418c4e0a01fa26e
