### ISSUE TITLE
Fix valuerror when providing wrong page parameter

### ISSUE THREAD

**Issue by jelly** [archlinux/archweb#326]
```
Traceback (most recent call last):
  File "/srv/http/archweb/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/http/archweb/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/http/archweb/packages/views/search.py", line 182, in search_json
    page = int(page) if page else 1

Exception Type: ValueError at /packages/search/json/
Exception Value: invalid literal for int() with base 10: '1\\'
Request information:
USER: AnonymousUser

GET:
name = 'ansible'
page = '1\\'
```

**Comment by jelly** [comment]
Fixed in https://www.youtube.com/watch?v=HC6QJsxRypQ
