### ISSUE TITLE
update_planet sometimes fails with http.client.* exceptions

### ISSUE THREAD

**Issue by foutrelis** [archlinux/archweb#439]
Not sure why, but this started happening in January 2023 (boot c3d320ef starts on Dec 26 21:41:36):

```
-- Boot c3d320ef37d24a598ee28dae72e71b3d --
Jan 04 11:43:19 archlinux.org python[2785304]: http.client.IncompleteRead: IncompleteRead(133601 bytes read, 6515 more expected)
Jan 06 00:00:15 archlinux.org python[3357436]: http.client.IncompleteRead: IncompleteRead(131121 bytes read, 8995 more expected)
Jan 06 11:06:08 archlinux.org python[3492558]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 06 19:09:59 archlinux.org python[3616568]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 08 21:35:52 archlinux.org python[179829]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 10 15:58:53 archlinux.org python[776283]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 11 05:06:21 archlinux.org python[975197]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 12 03:16:40 archlinux.org python[1300081]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 12 11:20:27 archlinux.org python[1408263]: http.client.IncompleteRead: IncompleteRead(1448 bytes read, 1871 more expected)
Jan 13 03:27:16 archlinux.org python[1696424]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 13 05:28:44 archlinux.org python[1729968]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 13 16:34:28 archlinux.org python[1964965]: http.client.IncompleteRead: IncompleteRead(1448 bytes read, 1871 more expected)
Jan 14 07:42:09 archlinux.org python[2191722]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 14 08:42:15 archlinux.org python[2206868]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 16 00:00:04 archlinux.org python[2888129]: http.client.IncompleteRead: IncompleteRead(1448 bytes read, 1871 more expected)
Jan 16 10:05:25 archlinux.org python[3044401]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 16 11:06:22 archlinux.org python[3063176]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 16 21:10:39 archlinux.org python[3279184]: http.client.IncompleteRead: IncompleteRead(1448 bytes read, 1871 more expected)
Jan 18 12:29:29 archlinux.org python[3921691]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 18 13:30:03 archlinux.org python[3938887]: http.client.RemoteDisconnected: Remote end closed connection without response
-- Boot be30531bcbea4dbda7696f0a9bb2e67c --
Jan 20 01:45:58 archlinux.org python[127375]: http.client.IncompleteRead: IncompleteRead(133628 bytes read, 8840 more expected)
Jan 20 03:47:16 archlinux.org python[148933]: http.client.IncompleteRead: IncompleteRead(133628 bytes read, 8840 more expected)
Jan 20 07:48:38 archlinux.org python[190888]: http.client.IncompleteRead: IncompleteRead(133628 bytes read, 8840 more expected)
Jan 21 01:57:47 archlinux.org python[466123]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 21 06:00:02 archlinux.org python[510002]: http.client.IncompleteRead: IncompleteRead(1448 bytes read, 1871 more expected)
Jan 21 14:02:29 archlinux.org python[617210]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 22 15:13:33 archlinux.org python[945925]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 23 07:20:45 archlinux.org python[1155972]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 23 08:21:30 archlinux.org python[1169534]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 23 09:22:02 archlinux.org python[1183587]: http.client.RemoteDisconnected: Remote end closed connection without response
Jan 23 14:24:35 archlinux.org python[1253964]: http.client.IncompleteRead: IncompleteRead(133630 bytes read, 8838 more expected)
Jan 23 15:25:11 archlinux.org python[1268261]: http.client.IncompleteRead: IncompleteRead(133629 bytes read, 8839 more expected)
```

Example tracebacks:

```
2023-01-23 09:22:02 -> DEBUG: Import new feed items for 'https://linderud.dev/tags/english/index.xml'
Traceback (most recent call last):
  File "/srv/http/archweb/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/http/archweb/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/srv/http/archweb/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/http/archweb/env/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/http/archweb/env/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/srv/http/archweb/planet/management/commands/update_planet.py", line 143, in handle
    self.parse_feed(feed)
  File "/srv/http/archweb/planet/management/commands/update_planet.py", line 51, in parse_feed
    feed = feedparser.parse(url, etag=etag)
  File "/srv/http/archweb/env/lib/python3.10/site-packages/feedparser/api.py", line 216, in parse
    data = _open_resource(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result)
  File "/srv/http/archweb/env/lib/python3.10/site-packages/feedparser/api.py", line 115, in _open_resource
    return http.get(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result)
  File "/srv/http/archweb/env/lib/python3.10/site-packages/feedparser/http.py", line 171, in get
    f = opener.open(request)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

```
2023-01-23 14:24:35 -> DEBUG: Import new feed items for 'https://shibumi.dev/posts/index.xml'
Traceback (most recent call last):
  File "/srv/http/archweb/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/http/archweb/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/srv/http/archweb/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/http/archweb/env/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/http/archweb/env/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/srv/http/archweb/planet/management/commands/update_planet.py", line 143, in handle
    self.parse_feed(feed)
  File "/srv/http/archweb/planet/management/commands/update_planet.py", line 51, in parse_feed
    feed = feedparser.parse(url, etag=etag)
  File "/srv/http/archweb/env/lib/python3.10/site-packages/feedparser/api.py", line 216, in parse
    data = _open_resource(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result)
  File "/srv/http/archweb/env/lib/python3.10/site-packages/feedparser/api.py", line 115, in _open_resource
    return http.get(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result)
  File "/srv/http/archweb/env/lib/python3.10/site-packages/feedparser/http.py", line 172, in get
    data = f.read()
  File "/usr/lib/python3.10/http/client.py", line 481, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.10/http/client.py", line 632, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(133630 bytes read, 8838 more expected)
```

**Comment by foutrelis** [comment]
Could be a kernel issue. We were seeing transfer speeds less than 2 MB/s with 6.1 kernels before 6.1.7. Let's see how the latter performs.

Closing for now.
